id: IA06B7B87
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T11:06:46+00:00'
last_modified: '2022-06-08T08:55:39.091631+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W20473
  title: སེ་ར་ཐེག་ཆེན་གླིང་གི་ལོ་རྒྱུས
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    '4869':
      image_group_id: I4787
      title: ''
      total_pages: 82
      order: 1
      base_file: 4869.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
